name: "go-client-ci"

on:
  push:
    branches:
      - master
      - release-*
    paths:
      - hugegraph-client-go/**
      - hugegraph-dist/**
      - .github/workflows/**
      - pom.xml
  pull_request:
    paths:
      - hugegraph-client-go/**
      - hugegraph-dist/**
      - .github/workflows/**
      - pom.xml

jobs:
  client-go-ci:
    uses: hugegraph/actions/.github/workflows/_toolchain_go_ci_reusable.yml@master
    with:
      java_version: '11'
      go_version: '1.x'
      use_stage: true
      settings_path: .github/configs/settings.xml
      prepare_command: |
        TRAVIS_DIR=hugegraph-client/assembly/travis
        "$TRAVIS_DIR"/install-hugegraph-from-source.sh 8c1ee71
      test_command: |
        go version
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
        cd hugegraph-client-go && make test
    secrets: inherit
