name: "java-client-ci"

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release-*
    paths:
      - hugegraph-client/**
      - hugegraph-dist/**
      - .github/workflows/**
      - pom.xml
  pull_request:
    paths:
      - hugegraph-client/**
      - hugegraph-dist/**
      - .github/workflows/**
      - pom.xml

jobs:
  client-ci:
    uses: hugegraph/actions/.github/workflows/_toolchain_java_ci_reusable.yml@master
    with:
      java_version: '11'
      use_stage: true
      settings_path: .github/configs/settings.xml
      compile_command: |
        mvn -e compile -pl hugegraph-client -Dmaven.javadoc.skip=true -ntp
      prepare_command: |
        TRAVIS_DIR=hugegraph-client/assembly/travis
        # TODO(@Thespica): test both servers of supporting gs and not supporting gs
        #                  when the server supports gs
        "$TRAVIS_DIR"/install-hugegraph-from-source.sh b7998c1
      test_command: |
        cd hugegraph-client && ls *
        mvn test -Dtest=UnitTestSuite -ntp
        mvn test -Dtest=ApiTestSuite
        mvn test -Dtest=FuncTestSuite
      codecov_file: target/jacoco.xml
    secrets: inherit
