name: "hubble-ci"

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release-*
    paths:
      - hugegraph-hubble/**
      - hugegraph-dist/**
      - hugegraph-loader/**
      - .github/workflows/**
      - pom.xml
  pull_request:
    paths:
      - hugegraph-hubble/**
      - hugegraph-dist/**
      - hugegraph-loader/**
      - hugegraph-client/**
      - .github/workflows/**
      - pom.xml

jobs:
  hubble-ci:
    uses: hugegraph/actions/.github/workflows/_toolchain_java_ci_reusable.yml@master
    with:
      java_version: '11'
      python_version: '3.11'
      use_stage: true
      settings_path: .github/configs/settings.xml
      compile_command: |
        mvn install -pl hugegraph-client,hugegraph-loader -am -Dmaven.javadoc.skip=true -DskipTests -ntp
        cd hugegraph-hubble && ls *
        mvn -e compile -Dmaven.javadoc.skip=true -ntp
      prepare_command: |
        TRAVIS_DIR=hugegraph-hubble/hubble-dist/assembly/travis

        python -m pip install -r "$TRAVIS_DIR"/requirements.txt
        cd hugegraph-hubble
        mvn package -Dmaven.test.skip=true
        cd apache-hugegraph-hubble-*
        cd bin
        ./start-hubble.sh -d
        ./stop-hubble.sh
        cd ../../../
        pwd
        "$TRAVIS_DIR"/install-hugegraph.sh 8c1ee71
      test_command: |
        mvn test -P unit-test -pl hugegraph-hubble/hubble-be -ntp
        cd hugegraph-hubble && ls
        CI=false hubble-dist/assembly/travis/run-api-test.sh
      codecov_file: target/site/jacoco/*.xml
    secrets: inherit
