name: "loader-ci"

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release-*
    paths:
      - hugegraph-loader/**
      - hugegraph-dist/**
      - .github/workflows/**
      - pom.xml
  pull_request:
    paths:
      - hugegraph-loader/**
      - hugegraph-dist/**
      - hugegraph-client/**
      - .github/workflows/**
      - pom.xml

jobs:
  loader-ci:
    uses: hugegraph/actions/.github/workflows/_toolchain_java_ci_reusable.yml@master
    with:
      java_version: '11'
      use_stage: true
      settings_path: .github/configs/settings.xml
      compile_command: |
        mvn install -pl hugegraph-client,hugegraph-loader -am -Dmaven.javadoc.skip=true -DskipTests -ntp
      prepare_command: |
        TRAVIS_DIR=hugegraph-loader/assembly/travis
        "$TRAVIS_DIR"/install-hadoop.sh
        "$TRAVIS_DIR"/install-mysql.sh load_test root
        "$TRAVIS_DIR"/install-hugegraph-from-source.sh 5b3d295
      test_command: |
        cd hugegraph-loader && ls
        mvn test -P unit -ntp
        mvn test -P file
        mvn test -P hdfs
        mvn test -P jdbc
        mvn test -P kafka
      codecov_file: target/jacoco.xml
    secrets: inherit
