name: "spark-connector-ci"

on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        required: true
      server-commit:
        type: string
        required: true
      server-ref:
        type: string
        required: true

jobs:
  spark-connector-ci:
    runs-on: ubuntu-latest
    env:
      USE_STAGE: 'true' # Whether to include the stage repository.
      TRAVIS_DIR: hugegraph-spark-connector/assembly/travis
    strategy:
      matrix:
        JAVA_VERSION: [ '11' ]

    steps:
      - name: Fetch Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 2

      - name: Setup Java environment
        uses: ./.github/actions/setup-java-env
        with:
          java-version: ${{ matrix.JAVA_VERSION }}
          distribution: 'temurin'
          use-stage: ${{ env.USE_STAGE }}

      - name: Compile
        run: |
          mvn install -pl hugegraph-client,hugegraph-spark-connector -am -Dmaven.javadoc.skip=true -DskipTests -ntp

      - name: Setup HugeGraph server
        uses: ./.github/actions/setup-hugegraph-server
        with:
          travis-dir: ${{ env.TRAVIS_DIR }}
          commit-id: ${{ inputs.server-commit }}
          fetch-ref: ${{ inputs.server-ref }}
          artifact-name: ${{ inputs.artifact-name }}
          mode: start

      - name: Run test
        run: |
          cd hugegraph-spark-connector && ls
          mvn test
