name: "spark-connector-ci"

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release-*
    paths:
      - hugegraph-spark-connector/**
      - hugegraph-dist/**
      - .github/workflows/**
      - pom.xml
  pull_request:
    paths:
      - hugegraph-spark-connector/**
      - hugegraph-dist/**
      - hugegraph-client/**
      - .github/workflows/**
      - pom.xml

jobs:
  spark-connector-ci:
    uses: hugegraph/actions/.github/workflows/_toolchain_java_ci_reusable.yml@master
    with:
      java_version: '11'
      use_stage: true
      settings_path: .github/configs/settings.xml
      compile_command: |
        mvn install -pl hugegraph-client,hugegraph-spark-connector -am -Dmaven.javadoc.skip=true -DskipTests -ntp
      prepare_command: |
        TRAVIS_DIR=hugegraph-spark-connector/assembly/travis
        "$TRAVIS_DIR"/install-hugegraph-from-source.sh 5b3d295
      test_command: |
        cd hugegraph-spark-connector && ls
        mvn test
    secrets: inherit
