name: "tools-ci"
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release-*
    paths:
      - hugegraph-tools/**
      - hugegraph-dist/**
      - .github/workflows/**
      - pom.xml
  pull_request:
    paths:
      - hugegraph-tools/**
      - hugegraph-dist/**
      - hugegraph-client/**
      - .github/workflows/**
      - pom.xml

jobs:
  tools-ci:
    uses: hugegraph/actions/.github/workflows/_toolchain_java_ci_reusable.yml@master
    with:
      java_version: '11'
      use_stage: true
      settings_path: .github/configs/settings.xml
      compile_command: |
        mvn install -pl hugegraph-client,hugegraph-tools -am -Dmaven.javadoc.skip=true -DskipTests -ntp
      prepare_command: |
        TRAVIS_DIR=hugegraph-tools/assembly/travis
        "$TRAVIS_DIR"/install-hugegraph-from-source.sh b7998c1
      test_command: |
        mvn test -Dtest=FuncTestSuite -pl hugegraph-tools -ntp
      codecov_file: target/jacoco.xml
    secrets: inherit
